In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [5]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
print(c.shape)

(2, 2, 2)


In [7]:
print(c.shape)

(2, 2, 2)


In [8]:
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [9]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [12]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Basic Data Types

In [13]:
a = np.arange(10)
print(a.dtype)

int64


In [14]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [15]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Othyer datatype

In [16]:
a= np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [17]:
a= np.array([True,False])
print(a.dtype)

bool


In [18]:
a= np.array(['Deeven kumar','Venu'])
print(a.dtype)

<U12


# Indexing and Slicing

In [19]:
a = np.arange(10)
print(a[5])

5


In [20]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [21]:
a[1,0] = 5 
print(a)

[[1 0 0]
 [5 2 0]
 [0 0 3]]


# Slicing

In [22]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(a[1:8:2])

[1 3 5 7]


In [24]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# Copies and viewing

In [25]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [26]:
print(np.shares_memory(a,b))

True


In [27]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [28]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [29]:
print(np.shares_memory(a,b))

False


In [30]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random Number Generator

In [31]:
a = np.random.randint(1,20,15)
print(a)

[ 2  7 17 17  2  5  9  9 19  1  8  8 17 14  8]


In [32]:
mask=(a%2==0)

In [33]:
mask_a = a[mask]
print(mask_a)

[ 2  2  8  8 14  8]


In [34]:
a[mask] = -1
print(a)

[-1  7 17 17 -1  5  9  9 19  1 -1 -1 17 -1 -1]


# Basic operations

In [35]:
import numpy as np

In [36]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [37]:
a = np.array([1,2,3,4])
print(a+2)

[3 4 5 6]


In [38]:
print(a**2)


[ 1  4  9 16]


# All Arthmetic Operations

In [39]:
b=np.ones(4)

In [40]:
print(b)

[1. 1. 1. 1.]


In [41]:
print(a+b)

[2. 3. 4. 5.]


In [42]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [43]:
print(c*c)
print('*****************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [44]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a==b)

[False False False False]


In [45]:
print(a>b)

[False False False False]


In [46]:
print(a<b)

[ True  True  True  True]


In [47]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


# Logical Operators

In [48]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


# Trigonometry / Transcdendental Functions

In [49]:
print(np.sin(a))

[0.8413 0.     0.8413 0.    ]


In [50]:
np.log(a)

C:\Users\user\AppData\Local\Temp\ipykernel_15800\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([  0., -inf,   0., -inf], dtype=float16)

In [51]:
print(np.exp(a))

[2.719 1.    2.719 1.   ]


# Basic Reductions

In [52]:
x = np.array([1,2,3,4])
print(np.sum(x))

10


In [53]:
x = np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [54]:
x.sum(axis=0) #column dimension

array([2, 4])

In [55]:
x.sum(axis=1) #row dimensions

array([3, 3])

In [56]:
x.sum()

np.int64(6)